# Generated by Django 5.0.6 on 2024-05-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('again', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
